services:
  api:
    build: .
    container_name: neval_be
    restart: unless-stopped
    ports:
      - "127.0.0.1:3013:3013"
    env_file:
      - .env
    networks:
      - postgres_network

networks:
  postgres_network:
    external: true