version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: workable-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workable
    ports:
      - "5432:5432"
    volumes:
      - workable_data:/var/lib/postgresql/data

volumes:
  workable_data:
