package database

import (
	"log"

	careermapping "github.com/bcc-intern-13/app-name-backend/internal/career_mapping/entity"
	"gorm.io/gorm"
)

func Seed(db *gorm.DB) {
	var count int64
	db.Model(&careermapping.CareerMappingQuestion{}).Count(&count)
	if count > 0 {
		log.Println("✅ Questions already seeded, skipping...")
		return
	}

	questions := []careermapping.CareerMappingQuestion{
		{
			Nomor:      1,
			Pertanyaan: "Ketika menghadapi masalah kompleks, kamu lebih suka?",
			PilihanA:   "Mencari solusi kreatif yang belum pernah dicoba",
			PilihanB:   "Menganalisis data dan mencari pola",
			PilihanC:   "Berdiskusi dengan orang lain untuk cari solusi",
			PilihanD:   "Membuat checklist dan mengikuti prosedur",
			SkorA:      []byte(`{"KR": 2, "TK": 1}`),
			SkorB:      []byte(`{"TK": 2, "AD": 1}`),
			SkorC:      []byte(`{"KO": 2, "ED": 1}`),
			SkorD:      []byte(`{"AD": 2, "OP": 1}`),
		},
		{
			Nomor:      2,
			Pertanyaan: "Aktivitas mana yang paling kamu nikmati?",
			PilihanA:   "Menggambar, menulis, atau membuat sesuatu",
			PilihanB:   "Coding, analisis data, atau riset",
			PilihanC:   "Mengajar, presentasi, atau memimpin diskusi",
			PilihanD:   "Mengorganisir, membuat laporan, atau mengelola jadwal",
			SkorA:      []byte(`{"KR": 2, "KO": 1}`),
			SkorB:      []byte(`{"TK": 2, "AD": 1}`),
			SkorC:      []byte(`{"ED": 2, "KO": 1}`),
			SkorD:      []byte(`{"AD": 2, "OP": 1}`),
		},
		{
			Nomor:      3,
			Pertanyaan: "Dalam kerja tim, kamu biasanya berperan sebagai?",
			PilihanA:   "Orang yang punya ide-ide unik dan kreatif",
			PilihanB:   "Orang yang menganalisis dan memecahkan masalah teknis",
			PilihanC:   "Orang yang menjaga hubungan dan komunikasi tim",
			PilihanD:   "Orang yang memastikan semua berjalan sesuai rencana",
			SkorA:      []byte(`{"KR": 2, "KO": 1}`),
			SkorB:      []byte(`{"TK": 2, "AD": 1}`),
			SkorC:      []byte(`{"KO": 2, "ED": 1}`),
			SkorD:      []byte(`{"OP": 2, "AD": 1}`),
		},
		{
			Nomor:      4,
			Pertanyaan: "Lingkungan kerja seperti apa yang paling cocok untukmu?",
			PilihanA:   "Studio kreatif yang penuh inspirasi",
			PilihanB:   "Lab atau kantor tech yang penuh tools canggih",
			PilihanC:   "Tempat yang banyak interaksi dengan orang",
			PilihanD:   "Kantor yang terstruktur dan sistematis",
			SkorA:      []byte(`{"KR": 2, "KO": 1}`),
			SkorB:      []byte(`{"TK": 2, "OP": 1}`),
			SkorC:      []byte(`{"KO": 2, "ED": 1}`),
			SkorD:      []byte(`{"AD": 2, "OP": 1}`),
		},
		{
			Nomor:      5,
			Pertanyaan: "Kamu lebih suka belajar dengan cara?",
			PilihanA:   "Bereksperimen dan mencoba hal baru",
			PilihanB:   "Membaca dokumentasi dan mengikuti tutorial",
			PilihanC:   "Diskusi kelompok dan belajar dari orang lain",
			PilihanD:   "Mengikuti langkah-langkah yang sudah terstruktur",
			SkorA:      []byte(`{"KR": 2, "TK": 1}`),
			SkorB:      []byte(`{"TK": 2, "AD": 1}`),
			SkorC:      []byte(`{"ED": 2, "KO": 1}`),
			SkorD:      []byte(`{"OP": 2, "AD": 1}`),
		},
		{
			Nomor:      6,
			Pertanyaan: "Proyek impianmu adalah?",
			PilihanA:   "Membuat karya seni, film, atau desain yang viral",
			PilihanB:   "Membangun aplikasi atau sistem yang dipakai jutaan orang",
			PilihanC:   "Program sosial yang membantu ribuan orang",
			PilihanD:   "Membangun bisnis yang terorganisir dan profitable",
			SkorA:      []byte(`{"KR": 2, "KO": 1}`),
			SkorB:      []byte(`{"TK": 2, "AD": 1}`),
			SkorC:      []byte(`{"ED": 2, "KO": 1}`),
			SkorD:      []byte(`{"AD": 2, "OP": 1}`),
		},
		{
			Nomor:      7,
			Pertanyaan: "Kamu merasa paling produktif saat?",
			PilihanA:   "Punya kebebasan berekspresi tanpa batas",
			PilihanB:   "Bekerja dengan data dan logika yang jelas",
			PilihanC:   "Berinteraksi dan berkolaborasi dengan orang lain",
			PilihanD:   "Mengikuti jadwal dan target yang jelas",
			SkorA:      []byte(`{"KR": 2, "KO": 1}`),
			SkorB:      []byte(`{"TK": 2, "AD": 1}`),
			SkorC:      []byte(`{"KO": 2, "ED": 1}`),
			SkorD:      []byte(`{"OP": 2, "AD": 1}`),
		},
		{
			Nomor:      8,
			Pertanyaan: "Skill apa yang ingin kamu kuasai?",
			PilihanA:   "Desain grafis, fotografi, atau penulisan kreatif",
			PilihanB:   "Programming, data science, atau cybersecurity",
			PilihanC:   "Public speaking, coaching, atau konseling",
			PilihanD:   "Manajemen proyek, akuntansi, atau logistik",
			SkorA:      []byte(`{"KR": 2, "KO": 1}`),
			SkorB:      []byte(`{"TK": 2, "OP": 1}`),
			SkorC:      []byte(`{"KO": 2, "ED": 1}`),
			SkorD:      []byte(`{"AD": 2, "OP": 1}`),
		},
		{
			Nomor:      9,
			Pertanyaan: "Saat ada waktu luang, kamu lebih suka?",
			PilihanA:   "Berkreasi — nulis, gambar, atau bikin konten",
			PilihanB:   "Belajar teknologi baru atau main game strategi",
			PilihanC:   "Hangout dan ngobrol dengan teman-teman",
			PilihanD:   "Beres-beres, merencanakan, atau journaling",
			SkorA:      []byte(`{"KR": 2, "KO": 1}`),
			SkorB:      []byte(`{"TK": 2, "AD": 1}`),
			SkorC:      []byte(`{"KO": 2, "ED": 1}`),
			SkorD:      []byte(`{"AD": 2, "OP": 1}`),
		},
		{
			Nomor:      10,
			Pertanyaan: "Kamu lebih bangga saat?",
			PilihanA:   "Karya kreatifmu diapresiasi banyak orang",
			PilihanB:   "Berhasil menyelesaikan masalah teknis yang rumit",
			PilihanC:   "Berhasil membantu dan menginspirasi orang lain",
			PilihanD:   "Berhasil menyelesaikan proyek tepat waktu dan sesuai target",
			SkorA:      []byte(`{"KR": 2, "KO": 1}`),
			SkorB:      []byte(`{"TK": 2, "AD": 1}`),
			SkorC:      []byte(`{"ED": 2, "KO": 1}`),
			SkorD:      []byte(`{"OP": 2, "AD": 1}`),
		},
		{
			Nomor:      11,
			Pertanyaan: "Kamu lebih suka pekerjaan yang?",
			PilihanA:   "Selalu berbeda dan penuh kejutan",
			PilihanB:   "Melibatkan teknologi dan inovasi terbaru",
			PilihanC:   "Berhubungan langsung dengan banyak orang",
			PilihanD:   "Punya prosedur jelas dan hasil yang terukur",
			SkorA:      []byte(`{"KR": 2, "KO": 1}`),
			SkorB:      []byte(`{"TK": 2, "OP": 1}`),
			SkorC:      []byte(`{"KO": 2, "ED": 1}`),
			SkorD:      []byte(`{"AD": 2, "OP": 1}`),
		},
		{
			Nomor:      12,
			Pertanyaan: "Tipe output kerja yang paling memuaskanmu?",
			PilihanA:   "Karya visual atau tulisan yang indah",
			PilihanB:   "Sistem atau aplikasi yang berjalan sempurna",
			PilihanC:   "Orang yang terbantu dan puas dengan pelayananmu",
			PilihanD:   "Laporan atau data yang akurat dan rapi",
			SkorA:      []byte(`{"KR": 2, "TK": 1}`),
			SkorB:      []byte(`{"TK": 2, "OP": 1}`),
			SkorC:      []byte(`{"ED": 2, "KO": 1}`),
			SkorD:      []byte(`{"AD": 2, "OP": 1}`),
		},
		{
			Nomor:      13,
			Pertanyaan: "Kamu lebih suka bekerja?",
			PilihanA:   "Sendiri dengan kebebasan penuh berkreasi",
			PilihanB:   "Dalam tim kecil yang fokus pada solusi teknis",
			PilihanC:   "Dalam tim besar dengan banyak kolaborasi",
			PilihanD:   "Dengan peran dan tanggung jawab yang jelas",
			SkorA:      []byte(`{"KR": 2, "AD": 1}`),
			SkorB:      []byte(`{"TK": 2, "OP": 1}`),
			SkorC:      []byte(`{"KO": 2, "ED": 1}`),
			SkorD:      []byte(`{"AD": 2, "OP": 1}`),
		},
		{
			Nomor:      14,
			Pertanyaan: "Ketika belajar hal baru, kamu lebih suka?",
			PilihanA:   "Langsung praktek dan eksplorasi sendiri",
			PilihanB:   "Memahami konsep dan teori di baliknya",
			PilihanC:   "Belajar dari mentor atau komunitas",
			PilihanD:   "Mengikuti kurikulum atau modul yang terstruktur",
			SkorA:      []byte(`{"KR": 2, "TK": 1}`),
			SkorB:      []byte(`{"TK": 2, "AD": 1}`),
			SkorC:      []byte(`{"ED": 2, "KO": 1}`),
			SkorD:      []byte(`{"OP": 2, "AD": 1}`),
		},
		{
			Nomor:      15,
			Pertanyaan: "Masalah apa yang paling ingin kamu selesaikan?",
			PilihanA:   "Kurangnya konten kreatif berkualitas di Indonesia",
			PilihanB:   "Akses teknologi yang belum merata",
			PilihanC:   "Kesenjangan pendidikan dan sosial",
			PilihanD:   "Inefisiensi proses bisnis dan operasional",
			SkorA:      []byte(`{"KR": 2, "KO": 1}`),
			SkorB:      []byte(`{"TK": 2, "OP": 1}`),
			SkorC:      []byte(`{"ED": 2, "KO": 1}`),
			SkorD:      []byte(`{"AD": 2, "OP": 1}`),
		},
		{
			Nomor:      16,
			Pertanyaan: "Feedback seperti apa yang paling berarti bagimu?",
			PilihanA:   "Karyamu menginspirasi dan menyentuh hati orang",
			PilihanB:   "Solusimu efisien dan technically sound",
			PilihanC:   "Kamu berhasil mengubah cara pikir seseorang",
			PilihanD:   "Pekerjaanmu akurat, tepat waktu, dan reliable",
			SkorA:      []byte(`{"KR": 2, "ED": 1}`),
			SkorB:      []byte(`{"TK": 2, "AD": 1}`),
			SkorC:      []byte(`{"ED": 2, "KO": 1}`),
			SkorD:      []byte(`{"OP": 2, "AD": 1}`),
		},
		{
			Nomor:      17,
			Pertanyaan: "Kamu lebih tertarik pada industri?",
			PilihanA:   "Media, entertainment, atau fashion",
			PilihanB:   "Teknologi, startup, atau riset",
			PilihanC:   "Pendidikan, NGO, atau kesehatan",
			PilihanD:   "Keuangan, manufaktur, atau logistik",
			SkorA:      []byte(`{"KR": 2, "KO": 1}`),
			SkorB:      []byte(`{"TK": 2, "AD": 1}`),
			SkorC:      []byte(`{"ED": 2, "KO": 1}`),
			SkorD:      []byte(`{"AD": 2, "OP": 1}`),
		},
		{
			Nomor:      18,
			Pertanyaan: "Cara kamu menghadapi deadline ketat?",
			PilihanA:   "Cari cara kreatif untuk kerja lebih efisien",
			PilihanB:   "Otomasi atau cari tools yang bisa bantu",
			PilihanC:   "Minta bantuan dan delegasi ke tim",
			PilihanD:   "Buat prioritas dan ikuti jadwal ketat",
			SkorA:      []byte(`{"KR": 2, "TK": 1}`),
			SkorB:      []byte(`{"TK": 2, "OP": 1}`),
			SkorC:      []byte(`{"KO": 2, "ED": 1}`),
			SkorD:      []byte(`{"OP": 2, "AD": 1}`),
		},
		{
			Nomor:      19,
			Pertanyaan: "5 tahun lagi, kamu ingin dikenal sebagai?",
			PilihanA:   "Kreator atau seniman yang punya karya berpengaruh",
			PilihanB:   "Expert teknologi atau engineer yang disegani",
			PilihanC:   "Pemimpin atau mentor yang banyak menginspirasi orang",
			PilihanD:   "Profesional yang reliable dan ahli di bidangnya",
			SkorA:      []byte(`{"KR": 2, "KO": 1}`),
			SkorB:      []byte(`{"TK": 2, "OP": 1}`),
			SkorC:      []byte(`{"ED": 2, "KO": 1}`),
			SkorD:      []byte(`{"AD": 2, "OP": 1}`),
		},
		{
			Nomor:      20,
			Pertanyaan: "Kamu paling termotivasi oleh?",
			PilihanA:   "Kebebasan berekspresi dan berkarya",
			PilihanB:   "Tantangan teknis yang kompleks",
			PilihanC:   "Dampak positif yang dirasakan orang lain",
			PilihanD:   "Pencapaian target dan hasil yang terukur",
			SkorA:      []byte(`{"KR": 2, "KO": 1}`),
			SkorB:      []byte(`{"TK": 2, "AD": 1}`),
			SkorC:      []byte(`{"ED": 2, "KO": 1}`),
			SkorD:      []byte(`{"AD": 2, "OP": 1}`),
		},
	}

	if err := db.Create(&questions).Error; err != nil {
		log.Fatal("❌ Failed to seed questions:", err)
	}

	log.Println("✅ Career mapping questions seeded successfully!")
}
